daily_assessments_enabled: true
pr_status_thresholds:
  critical: 1
  high: 1
  medium: 99999
  low: 99999
pr_status_force_pass_enabled: false
pr_status_enabled: true
pr_comments_enabled: true
pr_comments_on_passed_check_enabled: false
workspaces:
- name: default
  terraform_dir: .
terraform_enabled: false
cost_analysis_enabled: false
static_analysis_enabled: true
score_analysis_enabled: false
